### ISSUE TITLE
Minimum Rust Version

### ISSUE THREAD

**Issue by CodeLieutenant** [scylladb/scylla-rust-driver#1211]
In Cargo.toml `lints` are used, but this requires Rust >= 1.71 and the current MSRV is 1.70

```toml
[lints.rust]
unnameable_types = "warn"
unreachable_pub = "warn"
```

```
this Cargo does not support nightly features, but if you
switch to nightly channel you can pass
`-Zlints` to enable this feature.
```

Also we should add `rust-toolchain.toml` to indicate the MSRV and avoid conflicts with `Cargo.lock`, as installing dependencies with Rust greater then MSRV will break the packages
