### ISSUE TITLE
Hangs when using scylla in cluster

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#306]
When I run Scylla in docker, it run fine with this code:

```
pub async fn create_connection() -> Session {
    let session = SessionBuilder::new()
        .known_node("127.0.0.1:19042")
        .build()
        .await
        .unwrap();

    session.use_keyspace("mykeyspace", false).await.unwrap();

    session
}
```

I ran docker with `docker run --name scylla -p 19042:19042 -p 9042:9042 --rm scylladb/scylla`. This works fine.

But when I use docker compose or docker with scylla cluster, things don't work. This is the log (it hangs):

```
INFO scylla::transport::session: Shard-aware port detected: 19042
DEBUG scylla::transport::cluster: Requesting topology refresh
```

This is my docker compose file:

```
version: '3.2'

services:
  b-scylla:
    image: scylladb/scylla:4.4.4
    container_name: b-scylla
    volumes:
      - ./:/project
    ports:
      - 9042:9042
      - 19042:19042
      - 9160:9160

  b-scylla2:
    image: scylladb/scylla:4.4.4
    container_name: b-scylla2
    command:
      - "--seeds=b-scylla"

  b-scylla3:
    image: scylladb/scylla:4.4.4
    container_name: b-scylla3
    command:
      - "--seeds=b-scylla"
```

And I run it with `docker-compose up -d`. 

Alternatively, this will hang the code as well:

`docker run --name scylla -p 19042:19042 -p 9042:9042 --rm scylladb/scylla`
wait...
`docker run --name scylla2  --hostname scylla2 -d scylladb/scylla --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla)"`
